compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

# Help with checksum verification issues
checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.3.1.cjs
