compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

checksumBehavior: update

changesetBaseRefs:
  - "master"
  - "origin/master"
  - "upstream/master"
  - "main"
  - "origin/main"
  - "upstream/main"
  - "dev"
  - "origin/dev"
  - "upstream/dev"
  - "working"
  - "origin/working"
  - "upstream/working"